# Generated by Django 4.2.7 on 2024-07-01 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Activity type.', max_length=256, unique=True)),
                ('jenkins_url', models.CharField(help_text='Jenkins URL.', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='RUNNING', help_text='The status of activity.', max_length=256)),
                ('note', models.TextField(blank=True, help_text='Note about activity.', null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting_controller.activitytype')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ('-triggered_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityTypeDefaultPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of payload.', max_length=256)),
                ('value', models.CharField(help_text='Value of payload.', max_length=256)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting_controller.activitytype')),
            ],
            options={
                'unique_together': {('activity_type', 'name')},
            },
        ),
    ]
